on:
    push:
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release

jobs:
    build:
        name: python
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Compile OpenMP
              working-directory: ./
              env:
                OMP_NUM_THREADS: 16
              run: |
                sudo apt-get update; sudo apt-get install -y libomp5 libomp-dev
                echo OMP_NUM_THREADS:$OMP_NUM_THREADS
                echo OMP_SCHEDULE:$OMP_SCHEDULE
                echo OMP_DYNAMIC:$OMP_DYNAMIC
                echo OMP_NESTED:$OMP_NESTED

            - name: Install uv
              uses: astral-sh/setup-uv@v4
              with:
                version: "0.4.20"

            - name: "Set up Python"
              uses: actions/setup-python@v5
              with:
                python-version-file: "pyproject.toml"

            - name: Create lock
              run: uv sync --all-extras

            - name: Enable caching
              uses: astral-sh/setup-uv@v3
              with:
                enable-cache: true
                cache-dependency-glob: "uv.lock"

            - name: Install the project
              run: uv sync --all-extras

            - name: Build
              run: uv build --sdist --wheel

            - name: Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: |
                    dist/bsxplorer*



